namespace HomeCompanion.Knx;

/// <summary>
/// Instructs the <c>HomeCompanion.Knx.CodeGen</c> source generator to generate
/// <see cref="HomeCompanion.Base.Values.ValueBase{T}"/> properties on the decorated
/// <see langword="partial"/> class from a KNX configuration source.
/// </summary>
/// <remarks>
/// Two usage modes are supported:
/// <list type="number">
///   <item>
///     <term>ETS XML only</term>
///     <description>
///       Supply only <paramref name="exportFilePath"/>. Property names are derived by
///       CamelCasing the ETS group address labels. This is the legacy mode.
///     </description>
///   </item>
///   <item>
///     <term>AutoGen JSON (recommended)</term>
///     <description>
///       Supply <paramref name="autoGenFilePath"/> pointing to a <c>HomeCompanionKnxAutoGen.json</c>
///       file generated by <c>srf-network-cli knx-configuration --generate-homecompanion-autogen</c>.
///       Property names and DPTs are read from the JSON, which reflects the authoritative names in
///       <c>KnxDomainConfig.json</c>. When this path is provided <paramref name="exportFilePath"/> is
///       ignored and the ETS XML is not read by the generator.
///     </description>
///   </item>
/// </list>
/// All paths are resolved as absolute, or relative to the project directory when not rooted.
/// A missing file emits a warning diagnostic and produces no output (CI-safe).
/// Create a git-ignored <c>KnxValues.local.cs</c> to keep developer-local paths out of version control:
/// <code>
/// namespace HomeCompanion.Knx;
/// [KnxValuesFromEtsExport(autoGenFilePath: "/path/to/HomeCompanionKnxAutoGen.json")]
/// partial class KnxValues { }
/// </code>
/// </remarks>
[AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
public sealed class KnxValuesFromEtsExportAttribute : Attribute
{
    /// <summary>Absolute or project-relative path to the ETS group address export XML file.</summary>
    public string? ExportFilePath { get; }

    /// <summary>
    /// Absolute or project-relative path to the <c>HomeCompanionKnxAutoGen.json</c> file.
    /// When set, the generator uses this file instead of the ETS XML export.
    /// </summary>
    public string? AutoGenFilePath { get; }

    /// <param name="exportFilePath">Absolute or project-relative path to <c>GroupAddressExport.xml</c>.</param>
    /// <param name="autoGenFilePath">
    /// Optional absolute or project-relative path to <c>HomeCompanionKnxAutoGen.json</c>.
    /// When provided, <paramref name="exportFilePath"/> is ignored.
    /// </param>
    public KnxValuesFromEtsExportAttribute(string? exportFilePath = null, string? autoGenFilePath = null)
    {
        ExportFilePath = exportFilePath;
        AutoGenFilePath = autoGenFilePath;
    }
}
