namespace HomeCompanion.Integrations.OpenHab;

/// <summary>
/// Marker attribute to indicate that a class should be generated from OpenHAB Items. The actual properties are generated by a separate tool.
/// Mechanism:
/// <list type="bullet">
/// <item>Create in your local project a partial class OpenHabValues, file OpenHabValues.local.cs</item>
/// <item>Attribute the class with [OpenHabItemsImportAttribute] and specify the OpenHAB API URL and the code generation file path for the other part of the class, e.g. [OpenHabItemsImportAttribute("http://localhost:8080/rest", "~/myrepo/.../OpenHabValues.generated.cs")].</item>
/// <item>Use SRF.Network.Cli to run the code generation tool, which will generate the other part of the class in the specified file.</item>
/// </list>
/// </summary>
/// <remarks>
/// Not used as of now. SRF.Network.Cli should not depend on this assembly.
/// Local tools may depend on this assembly and could use this attribute.
/// Dynamically loading the target assembly may be an option, but is not implemented at this point.
/// Instead, the code generation tool uses its own configuration to determine the OpenHAB API URL and the code generation file path.
/// </remarks>
[AttributeUsage(AttributeTargets.Class, AllowMultiple = false)]
public class OpenHabItemsImportAttribute : Attribute
{
    public string OpenHabApiUrl { get; set; } = "http://asgard.fu:8080/rest";
    public string CodeGenFilePath { get; set; } = "OpenHabValues.generated.cs";

    public OpenHabItemsImportAttribute(string openHabApiUrl, string codeGenFilePath)
    {
        OpenHabApiUrl = openHabApiUrl;
        CodeGenFilePath = codeGenFilePath;
    }
}