namespace HomeCompanion.Integrations.OpenHab;

public partial class OpenHabValues
{
    // This file is intentionally left blank. The actual properties are generated by a separate tool.
    // As KNX and OpenHab configuration mgt is not integrated into HomeCompanion at this point, `SRF.Network.Cli` is used. See its `kc -hc` command for details.
}
