using System.Text;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using SRF.Knx.Config;
using SRF.Knx.Core;
using SRF.Knx.Core.DPT;

namespace HomeCompanion.Support.Knx;

/*
On the journey to get UnitsNet quantity types working for KNX DPTs and IValueBusEndpointMapping:
a) architectural question: where's the transition from the PDT encoder/decoder to the Quantity type?
    a.1) IValue resp. implementations like ValueBase<T> need to support UnitsNet quantity types as T.
    a.2) the DPT is fixed to the unit by master data and the PDT encoder/decoder is tied to it, taking/returning values in that unit in the DPT's C# value type.
    a.3) IValueBusEndpointMapping is the only place where the DPT encoder/decoder is used, and it returns a .NET type, not a quantity type
    a.4) SRF.Knx.* preferrably do not depend on UnitsNet. However, HomeCompanion.Values or .Base can/do already depend on UnitsNet.
b) additional considerations:
    b.1) OpenHAB feeds quantity types as string that need to be parsed into IValue<Quantity>.
c) architectural options:
    c.1) IValueBusEndpointMapping can be made generic on T, and the DPT encoder/decoder can be used to convert to the DPT's C# value type, and then a conversion to the quantity type can be done in the mapping.
        This requires a mapping from DPT to quantity type, which can be done in the KnxValues code generation part with generics on e.g. the mapper used for the ValueBase<T> property.
*/

/// <summary>
/// Generates the content of <c>KnxValues.generated.cs</c> — a <c>partial class KnxValues</c>
/// with one <c>ValueBase&lt;T&gt;</c> property per KNX group address — from a
/// <see cref="KnxValueConfiguration"/> mapping.
/// </summary>
/// <remarks>
/// Invoke via <c>hccli k --home-companion-code-gen</c>. The output path is
/// configured via <see cref="KnxSystemConfigOptions.HomeCompanionCodeGenFile"/>.
/// </remarks>
public class KnxValuesCodeGenerator(
    IOptions<KnxSystemConfigOptions> options,
    IDptFactory dptFactory,
    ILogger<KnxValuesCodeGenerator> logger
)
{
    private readonly KnxSystemConfigOptions config = options.Value;

    /// <summary>
    /// Generates the full content of <c>KnxValues.generated.cs</c>.
    /// </summary>
    /// <param name="entries">
    /// Mapping of KNX group address strings (e.g. <c>"1/2/3"</c>) to their auto-gen entries.
    /// Produced by <see cref="IKnxConfigFactory.GenerateHomeCompanionAutoGen"/>.
    /// </param>
    /// <returns>Full C# source text ready to be written to disk.</returns>
    public string Generate(Dictionary<string, KnxValueConfiguration> entries)
    {
        var className = config.HomeCompanion.KnxValuesClassName ?? "KnxValues";
        var namespaceName = config.HomeCompanion.GeneratedValuesClassesNamespace ?? "HomeCompanion.Local.Values";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by 'hccli k --home-companion-code-gen'");
        sb.AppendLine("// Do not edit manually. Regenerate when KNX group address configuration changes.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using HomeCompanion.Values;");
        sb.AppendLine("using HomeCompanion.Integrations.Knx;");
        sb.AppendLine("using HomeCompanion.Integrations.OpenHab;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.Logging;");
        sb.AppendLine("using SRF.Knx.Core;");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine();
        sb.AppendLine($"partial class {className}");
        sb.AppendLine("{");

        var usedNames = new HashSet<string>(StringComparer.Ordinal);

        foreach (var kvp in entries)
        {
            if (string.IsNullOrWhiteSpace(kvp.Value.Dpt))
            {
                logger.LogWarning($"DPT must be specified for group address {kvp.Key} with property name {kvp.Value.PropertyName} to generate the corresponding ValueBase property in KnxValues.generated.cs.");
                continue;
            }
            var address = kvp.Key;
            var entry = kvp.Value;
            var dpt = dptFactory.Get(entry.Dpt);
            var csType = GetCSharpType(dpt);
            var propName = MakeUnique(entry.PropertyName, usedNames);
            var addOpenHabInitializationMapping = entry.WantsOpenHabInitialization && !string.IsNullOrWhiteSpace(entry.OpenHabItemName);
            var openHabItemName = entry.OpenHabItemName;
            var summaryText = (!string.IsNullOrWhiteSpace(entry.Label)
                ? $"{EscapeXmlComment(entry.Label)}"
                : $"{EscapeXmlComment(entry.PropertyName)}") + $" (<c>{address}</c>" + (string.IsNullOrWhiteSpace(entry.Dpt) ? ")" : $", {entry.Dpt})");

            // Determine bus communication flags for the generated KnxBusEndpointMapping based on the entry's Communication property.
            var commFlags = GetKnxBusMappingCommunicationFlags(entry);

            sb.AppendLine($"    /// <summary>{summaryText}</summary>");
            if (!string.IsNullOrWhiteSpace(entry.Description))
                sb.AppendLine($"    /// <remarks>{EscapeXmlComment(entry.Description!)}</remarks>");
            sb.AppendLine($"    public ValueBase<{csType}> {propName} {{ get; }} = new(loggerFactory.CreateLogger<ValueBase<{csType}>>())");
            sb.AppendLine("    {");
            sb.AppendLine($"       Name = \"{propName}\",");
            sb.AppendLine($"       Label = {(string.IsNullOrWhiteSpace(entry.Label) ? "null" : $"\"{entry.Label}\"")},");
            sb.AppendLine("       BusMappings = new Dictionary<object, IValueBusEndpointMapping>");
            sb.AppendLine("       {");
            AppendKnxBusMapping(sb, kvp, indentLevel: 3);
            AppendOpenHabBusMapping(sb, kvp, indentLevel: 3);
            sb.AppendLine("       }");
            sb.AppendLine("    };");
            sb.AppendLine();
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private void AppendKnxBusMapping(StringBuilder sb, KeyValuePair<string, KnxValueConfiguration> kvp, int indentLevel)
    {
        var address = kvp.Key;
        var entry = kvp.Value;
        var commFlags = GetKnxBusMappingCommunicationFlags(entry);
        AppendLineIndented(sb,
            $"[KnxBusEndpointMapping.BusId] = new KnxBusEndpointMapping(\"{address}\", \"{entry.Dpt}\", dptFactory) {{ Communication = {commFlags} }},",
            indentLevel);
    }

    private void AppendOpenHabBusMapping(StringBuilder sb, KeyValuePair<string, KnxValueConfiguration> kvp, int indentLevel)
    {
        var entry = kvp.Value;
        if (!entry.WantsOpenHabInitialization || string.IsNullOrWhiteSpace(entry.OpenHabItemName))
            return;
        AppendLineIndented(sb,
            $"[OpenHabBusEndpointMapping.BusId] = new OpenHabBusEndpointMapping(\"{entry.OpenHabItemName}\") {{ Communication = BusCommunication.Initialize }},",
            indentLevel);
    }

    private static void AppendLineIndented(StringBuilder sb, string line, int indentLevel)
    {
        var indent = new string(' ', indentLevel * 4);
        sb.AppendLine($"{indent}{line}");
    }

    private static string GetKnxBusMappingCommunicationFlags(KnxValueConfiguration entry)
    {
        var commFlagsList = new List<string>();
        if (entry.Communication.HasFlag(KnxObjectBusCommunication.Read)) commFlagsList.Add("BusCommunication.AnswerReadRequests");
        if (entry.Communication.HasFlag(KnxObjectBusCommunication.Write) || entry.Communication.HasFlag(KnxObjectBusCommunication.Update)) commFlagsList.Add("BusCommunication.Receive");
        if (entry.Communication.HasFlag(KnxObjectBusCommunication.Transmit)) commFlagsList.Add("BusCommunication.Transmit");
        if (entry.Communication.HasFlag(KnxObjectBusCommunication.Initialize)) commFlagsList.Add("BusCommunication.Initialize");
        if (commFlagsList.Count == 0)
            commFlagsList.Add("BusCommunication.None");
        return string.Join(" | ", commFlagsList);
    }

    // -------------------------------------------------------------------------
    // DPT → C# type mapping  (stable per KNX specification) TODO/or not?: move to SRF.Knx.Core.DPT namespace and make it public for reuse in other contexts (e.g. KnxValueFactory); and use the existing DPT/PDT master data (or rather PDT encoder type?) to determine the C# type instead of hardcoding it here.
    // -------------------------------------------------------------------------

    private record DptToCSharpTypeMapping(int dptMain, int dptSub, string CSharpType);
    private static DptToCSharpTypeMapping[]? _dptToCSharpTypeMappingOverrides =
    [
        new(5, 4, "double"), // Very special case: DPST-5-4 (angle) must be native double instead of byte or int32
    ];
    private readonly IDptFactory dptFactory = dptFactory;
    private readonly ILogger<KnxValuesCodeGenerator> logger = logger;

    private bool IsUnitsNetQuantityType(DptBase dpt)
    {
        if ( dpt is DptSimple dptSimple && dptSimple.ApplicationType is not null)
        {
            var appType = dptSimple.ApplicationType;
            // Check if the application type is a UnitsNet quantity type
            return appType.Namespace?.StartsWith("UnitsNet") ?? false;
        }
        return false;
    }

    /// <summary>
    /// Maps a DPT main number to the C# value type used in <c>ValueBase&lt;T&gt;</c>.
    /// DPT strings have the form <c>"DPST-X-Y"</c> or <c>"DPT-X"</c>.
    /// </summary>
    /// <remarks>
    /// Some DPST have in their numeric format master data a Coefficient defined.
    /// For those, we want to apply the coefficient during encoding and decoding to provide a more intuitive value range for the users of the generated properties. This method ensures that the generated property names are unique, even if multiple group addresses share the same label or property name in the input mapping.
    /// The scaling results in the fact that decimal remains decimal, but all other type become double in the generated code to avoid confusion about the actual value range and precision of the generated properties, which would be different from the underlying DPT value type for types other than double and decimal.
    /// </remarks>
    /// <remarks>
    /// TODO: move into a shared service in SRF.Knx.Core.DPT namespace and make it public for reuse in other contexts (e.g. KnxValueFactory); and use the existing DPT master data to determine the C# type instead of hardcoding it here.
    /// TODO: add support for DPTs with Coefficient != 1.0 to return double for all types except double and decimal, to reflect the fact that the value range and precision of the generated properties will be different from the underlying DPT value type due to the scaling.
    /// TODO: add support for UnitsNet types for DPTs with physical units, e.g. DPT-9-1 (temperature) should map to UnitsNet.Temperature instead of float.
    /// </remarks>
    private static string GetCSharpType(DptBase dpt)
    {
        /*
        if (string.IsNullOrEmpty(dpt))
            return "byte[]";

        var parts = dpt!.Split('-');
        if (parts.Length < 2 || !int.TryParse(parts[1], out var main))
            return "byte[]";
        */
        var main = dpt.Id.Main;
        var sub = dpt.Id.Sub;

        if (_dptToCSharpTypeMappingOverrides is not null)
        {
            var overrideMapping = _dptToCSharpTypeMappingOverrides.FirstOrDefault(m => m.dptMain == main && m.dptSub == sub);
            if (overrideMapping is not null)
                return overrideMapping.CSharpType;
        }

        var nativeType = main switch
        {
            1 => "bool",      // 1-bit switch/boolean
            2 => "byte",      // 2-bit controlled
            3 => "byte",      // 4-bit dimming
            4 => "char",      // 1-byte character
            5 => "byte",      // 1-byte unsigned (0–100 %, angles, …), see exceptions & scaling related deviations below
            6 => "sbyte",     // 1-byte signed
            7 => "ushort",    // 2-byte unsigned
            8 => "short",     // 2-byte signed
            9 => "float",     // KNX 2-byte float (EIS 5)
            10 => "byte[]",   // Time of day (complex)
            11 => "byte[]",   // Date (complex)
            12 => "uint",     // 4-byte unsigned
            13 => "int",      // 4-byte signed
            14 => "float",    // IEEE 754 4-byte float
            16 => "string",   // ISO 8859-1 character string
            17 => "byte",     // Scene number
            18 => "byte",     // Scene control
            19 => "byte[]",   // Date & time (complex), TODO: change into a DateTimeOffset type and implement proper encoding/decoding in the DPT implementation
            _ => main >= 20 && main <= 29 ? "byte" : "byte[]"
        };

        if (dpt.IsScaledNumeric)
        {
            if (dpt is DptSimple dptSimple && dptSimple.NumericInfo?.Coefficient is not null && dptSimple.NumericInfo.Coefficient != 1.0)
            {
                // If a coefficient is defined for a numeric DPT, use double for all types except double and decimal to reflect the fact that the value range and precision of the generated properties will be different from the underlying DPT value type due to the scaling.
                if (nativeType != "double" && nativeType != "decimal")
                    return "double";
            }
            return dpt.ApplicationType.Name;
        }
        return nativeType;
    }

    private static string MakeUnique(string name, HashSet<string> used)
    {
        if (used.Add(name))
            return name;
        for (var i = 2; ; i++)
        {
            var candidate = $"{name}_{i}";
            if (used.Add(candidate))
                return candidate;
        }
    }

    private static string EscapeXmlComment(string text) =>
        text
            .Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;")
            .Replace("\n", "<br/>")
            .Replace("\r", "");
}
